language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.4
  - 8.0

env:
  - # dev
  - COMPOSER_EXTRA_ARGS="--prefer-stable"
  - COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: COMPOSER_EXTRA_ARGS="--prefer-stable" COVERAGE="--coverage ./coverage.xml --coverage-src ./src" TESTER_RUNTIME="phpdbg"
    - php: 7.4
      env: COMPOSER_EXTRA_ARGS="--prefer-stable" PHPSTAN=1
  exclude:
    - php: 7.4
      env: COMPOSER_EXTRA_ARGS="--prefer-stable"
  allow_failures:
    - env:

install:
  - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist $COMPOSER_EXTRA_ARGS
  - if [ "$COVERAGE" != "" ]; then travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi

script:
  - if [ "$PHPSTAN" = "1" ]; then vendor/bin/phpstan analyse --ansi --no-progress -l7 -c phpstan.neon src; fi
  - vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - vendor/bin/tester $COVERAGE -s -p ${TESTER_RUNTIME:-php} -c ./tests/php.ini-unix ./tests/

after_script:
  - if [ "$COVERAGE" != "" ]; then php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true; fi

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
